#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1
#include "c2000BoardSupport.h"
#include "DSP281x_Device.h"
#include "DSP281x_GlobalPrototypes.h"
#include "c2000SchedulerTimer.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE TI F281x
#define MW_RTOS Baremetal
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 1
#define MW_RUNTIME_DEVICEID 0
#define MW_RUNTIME_FLASHLOAD 1
#define MW_RUNTIME_LOADCOMMANDARG E:/DATA/DSP_Tutorial/Matlab_pid_C2000/pid_C2000/Config_matlab.ccxml
#define MW_TARGETLINKOBJ_USECUSTOMLINKER 1
#define MW_TARGETLINKOBJ_NAME $(TARGET_ROOT)/src/c2812.cmd
#define MW_CLOCKING_CPUCLOCKRATEMHZ 150
#define MW_CLOCKING_OSCCLK 30
#define MW_CLOCKING_AUTOSETPLLSETTINGS 1
#define MW_CLOCKING_PLLCR 0
#define MW_CLOCKING_DIVSEL 0
#define MW_CLOCKING_CLOSESTCPUCLOCK 150
#define MW_CLOCKING_LSPCLKDIV 2
#define MW_CLOCKING_LSPCLK 37.5
#define MW_CLOCKING_HSPCLKDIV 1
#define MW_CLOCKING_HSPCLK 75
#define MW_ADC_ADCLKPS 6
#define MW_ADC_CPS 0
#define MW_ADC_ADCCLK 6.250000
#define MW_ADC_ACQ_PS 12
#define MW_ADC_ACQUISITIONWINDOW 2.080000
#define MW_ECAN_MODULECLOCKFREQUENCY 150
#define MW_ECAN_BAUDRATEPRESCALER 10.000000
#define MW_ECAN_TSEG1 6
#define MW_ECAN_TSEG2 4
#define MW_ECAN_BAUDRATE 1000000
#define MW_ECAN_SBG 0
#define MW_ECAN_SJW 1
#define MW_ECAN_SAM 0
#define MW_ECAN_ENHANCEDCANMODE 1
#define MW_ECAN_SELFTESTMODE 0
#define MW_SPI_MODE 0
#define MW_SPI_USERBAUDRATE 460800
#define MW_SPI_BAUDRATEFACTOR 80.000000
#define MW_SPI_BAUDRATE 462963.000000
#define MW_SPI_DATABITS 15
#define MW_SPI_CLOCKPOLARITY 0
#define MW_SPI_CLOCKPHASE 0
#define MW_SPI_SUSPENSIONMODE 2
#define MW_SPI_ENABLELOOPBACK 0
#define MW_SPI_TXINTERRUPTENABLE 0
#define MW_SPI_FIFOINTERRUPTLEVEL_TX 0
#define MW_SPI_RXINTERRUPTENABLE 0
#define MW_SPI_FIFOINTERRUPTLEVEL_RX 16
#define MW_SPI_FIFOENABLE 0
#define MW_SPI_FIFOTRANSMITDELAY 0
#define MW_SPI_FIFO_LEVEL 16.000000
#define MW_SCI_A_ENABLELOOPBACK 0
#define MW_SCI_A_SUSPENSIONMODE 2
#define MW_SCI_A_NUMBEROFSTOPBITS 0
#define MW_SCI_A_PARITYMODE 0
#define MW_SCI_A_CHARACTERLENGTHBITS 0
#define MW_SCI_A_USERBAUDRATE 115200
#define MW_SCI_A_BAUDRATEPRESCALER 40.000000
#define MW_SCI_A_BAUDRATE 114329.000000
#define MW_SCI_A_COMMUNICATIONMODE 0
#define MW_SCI_A_BLOCKINGMODE 0
#define MW_SCI_A_DATABYTEORDER 0
#define MW_SCI_A_DATASWAPWIDTH 0
#define MW_SCI_B_ENABLELOOPBACK 0
#define MW_SCI_B_SUSPENSIONMODE 2
#define MW_SCI_B_NUMBEROFSTOPBITS 0
#define MW_SCI_B_PARITYMODE 0
#define MW_SCI_B_CHARACTERLENGTHBITS 0
#define MW_SCI_B_USERBAUDRATE 115200
#define MW_SCI_B_BAUDRATEPRESCALER 40.000000
#define MW_SCI_B_BAUDRATE 114329.000000
#define MW_SCI_B_COMMUNICATIONMODE 0
#define MW_SCI_B_BLOCKINGMODE 0
#define MW_SCI_B_DATABYTEORDER 0
#define MW_SCI_B_DATASWAPWIDTH 0
#define MW_WATCHDOG_ENABLE_WATCHDOG 0
#define MW_WATCHDOG_WATCHDOGCLOCK 0
#define MW_WATCHDOG_TIME_PERIOD 0.004369
#define MW_WATCHDOG_WATCHDOGEVENT 0
#define MW_GPIO_QUALPRDA 0
#define MW_GPIO_QUALPRDB 0
#define MW_GPIO_QUALPRDD 0
#define MW_GPIO_QUALPRDE 0
#define MW_DATAVERSION 2016.02

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
